### ISSUE TITLE
getSectorParameter crashes Mombot

### ISSUE THREAD

**Issue by MicroBlaster** [TW2002/twxp#15]
![image](https://user-images.githubusercontent.com/3355654/32356505-87d4a308-c003-11e7-9d1e-4e04ca901311.png)

**Comment by MicroBlaster** [comment]
This is still an issue:
Star Killer: Unknown script run-time error 'MOM_BOT3_1043K.TS': , line 11328
Star Killer: heres whats on that line:           setSectorParameter 2 "FIG_COUNT" 0

**Comment by MicroBlaster** [comment]
![image](https://user-images.githubusercontent.com/3355654/37827150-59e1aac0-2e64-11e8-831b-074c61be03a7.png)

**Comment by Hotblack-Desiato** [comment]
I've noticed and fixed this problem in several scripts now.  I'll try to report here more often when I notice stuff like this.

**Comment by MicroBlaster** [comment]
TWX Proxy will now ignore requests for a fighter count on sector #2.
